version: '3.8'
services:
  app:
    container_name: app-springboot-postgresql
    image: app-springboot-postgresql
    build: ./
    network_mode: "host"
    ports:
      - "8080:8080"
    environment:
      - MYAPP_JDBC_URL=jdbc:postgresql://db:5432/somedb
      - MYAPP_JDBC_USER=postgres
      - MYAPP_JDBC_PASS=root
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=room_db
