version: '2'
services:
  postges:
    image: postgres:10.1
    ports:
    - 5432:5432
    restart: always
  app:
    image: app
    depends_on:
      - postges
    ports:
    - 8080:8080
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=room_db
    restart: always